name: Build and publish to npm registery

on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 17
                  cache: yarn
                  registry-url: https://registry.npmjs.org/
            - run: yarn
            - run: yarn npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
